version: "3.3"
services: 
  app:
    image: nginx:latest
    ports:
        - 80:80
    volumes:
        - ./html:/code:ro
        - ./config/localhost.conf:/etc/nginx/conf.d/default.conf:ro
        - ./config/demo-vhost.conf:/etc/nginx/conf.d/demo-vhost.conf:ro
    depends_on:
        - php-7
        - php-5
  php-7:
    image: php:7.2-fpm
    ports:
      - 9000
    volumes:
      - ./html/localhost:/scripts
  php-5:
    image: php:5.6-fpm
    ports:
      - 9000
    volumes:
      - ./html/demo-vhost:/scripts
  php-5-localhost:
    image: php:5.6-fpm
    ports:
      - 9000
    volumes:
      - ./html/localhost:/scripts
      - ./config/www.conf:/usr/local/etc/php-fpm.d/www.conf:ro