version: "3.3"
services:
    app:
        image: nginx:latest
        ports:
            - 80:80
        volumes:
            - ./html:/code:ro
            - ./config/default.conf:/etc/nginx/conf.d/default.conf:ro
    php:
        image: php:7.2-fpm
        ports:
            - 9000
        volumes:
            - ./html:/var/www/html
